name = "appimagehandler"
uuid = "161d85ee-bc2c-4f72-96fc-6abe13a8da0b"
authors = ["Luke Bemish <lukebemish@gmail.com>"]
version = "0.0.1"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
